# Generated by Django 3.2.5 on 2021-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('role', models.CharField(max_length=16, unique=True)),
            ],
        ),
    ]
