# Generated by Django 3.2.5 on 2021-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=16)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
